### ISSUE TITLE
Clear Digits session by logging out

### ISSUE THREAD

**Issue by 1l0** [dghubble/gologin#7]
When a user logged out [whoam.io](https://whoam.io/profile),
```
www.digits.com: digits_sso_session
```
above cookie should be cleared as well.

**Comment by dghubble** [comment]
I apologize for the delay, just saw this. 

The digits.com service sets the digits_sso_session cookie as the "remember me" cookie so that if you Login with Digits to another site using the same browser, the user doesn't have to confirm another SMS. Websites using Digits (such as whoam.io) don't have control over those cookies.
